### ISSUE TITLE
Xpath parse error

### ISSUE THREAD

**Issue by jstaerk** [DesignLiquido/xslt-processor#28] opened 2019-07-17 15:22 UTC
Hi,

when I try to

```
const XMLXRString = xsltProcess(
    xmlParse(zugferdInvoice),
    xmlParse(XSLTcii2xr)
);
```
with [zugferdInvoice](http://www.mustangproject.org/files/zugferd-invoice.xml) and [XSLTcii2xr](https://github.com/itplr-kosit/xrechnung-visualization/blob/master/src/xsl/cii-xr.xsl)

I seem to get a 
```
/viewer/node_modules/xslt-processor/dist/xslt-processor.js:1 Uncaught XPath parse error /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:SellerTradeParty/ram:SpecifiedTaxRegistration/ram:ID[@schemeID=('VA', 'VAT')]:
/
RelativeLocationPath
/
Step
[
Expr
=
(
Expr
ArgumentRemainder
)
]
```

any idea anyone?

**Comment by eechava** [comment] 2020-10-08 22:21
Same error in here

**Comment by jstaerk** [comment] 2021-02-20 14:37
In the meantime you could use the visualize feature that is based on that but if there are xpath parse errors that would rather be a report for kosit, wouldn't it?

**Comment by leonelsanchesdasilva** [comment] 2023-07-13 21:20
I was not able to reproduce this. I had another error:

```
'not implemented: include'
```

`xsl:include` is in our backlog to be implemented. 

For now I'll close this. Feel free to reopen if we can get a pair or XML/XSLT files to reproduce the issue.

**Closed by leonelsanchesdasilva** 2023-07-13 21:20 UTC
Labels: bug
